### Lemmatization for simple csv

In [1]:
import re
import pandas as pd
from pymystem3 import Mystem

m = Mystem()

In [2]:
test = 'Попробуй этих мягких французских булок'
lemma = m.lemmatize(test)
print(lemma) # list output

['попробовать', ' ', 'этот', ' ', 'мягкий', ' ', 'французский', ' ', 'булка', '\n']

In [3]:
import os
os.getcwd()

'/Users/tonya/Documents/ucl/kjetsaa/scr'

In [4]:
# os.chdir('../periodicals')
# os.listdir()

In [8]:
df = pd.read_csv('../data/poetree_ru_19c_tokens.csv')
df.head()

,Unnamed: 0,corpus,id_poem,id,title,year_created_from,year_created_to,id_author,author_name,word
0,1,ru,33734,br1-105,К...,1821.0,1821.0,220,Baratynskij E.A.,приятель
1,2,ru,33734,br1-105,К...,1821.0,1821.0,220,Baratynskij E.A.,строгий
2,3,ru,33734,br1-105,К...,1821.0,1821.0,220,Baratynskij E.A.,ты
3,4,ru,33734,br1-105,К...,1821.0,1821.0,220,Baratynskij E.A.,не
4,5,ru,33734,br1-105,К...,1821.0,1821.0,220,Baratynskij E.A.,прав

In [9]:
len(df)

1124893

In [10]:
# check if some of the cells are in wrong type / empty
df = df.loc[df.word.apply(lambda x: not isinstance(x, (float, int)))]

In [11]:
len(df)

1124893

In [12]:
# lemmatization
df['lemma'] = df['word'].apply(m.lemmatize)
df['lemma'] = [''.join(map(str, l)) for l in df['lemma']] 
df['lemma'] = df['lemma'].str.replace('\n', '', regex = True)

In [13]:
# run analysis
df['analysis'] = df['word'].apply(m.analyze)

In [14]:
df.tail()

,Unnamed: 0,corpus,id_poem,id,title,year_created_from,year_created_to,id_author,author_name,word,lemma,analysis
1124888,1124889,ru,44257,pu-coll-07,Баллада,1819.0,1819.0,347,Zhukovskij V.A.,нам,мы,"[{'analysis': [{'lex': 'мы', 'gr': 'SPRO,мн,1-..."
1124889,1124890,ru,44257,pu-coll-07,Баллада,1819.0,1819.0,347,Zhukovskij V.A.,только,только,"[{'analysis': [{'lex': 'только', 'gr': 'PART='..."
1124890,1124891,ru,44257,pu-coll-07,Баллада,1819.0,1819.0,347,Zhukovskij V.A.,с,с,"[{'analysis': [{'lex': 'с', 'gr': 'S,сокр=(пр,..."
1124891,1124892,ru,44257,pu-coll-07,Баллада,1819.0,1819.0,347,Zhukovskij V.A.,ней,она,"[{'analysis': [{'lex': 'она', 'gr': 'SPRO,ед,3..."
1124892,1124893,ru,44257,pu-coll-07,Баллада,1819.0,1819.0,347,Zhukovskij V.A.,нерозно,нерозный,"[{'analysis': [{'lex': 'нерозный', 'qual': 'ba..."

In [15]:
df = df.drop('Unnamed: 0', axis = 1)
# df = df.drop('text', axis = 1)

In [16]:
print(df.head(1000))

    corpus  id_poem       id                               title  \
0       ru    33734  br1-105                                К...
1       ru    33734  br1-105                                К...
2       ru    33734  br1-105                                К...
3       ru    33734  br1-105                                К...
4       ru    33734  br1-105                                К...
..     ...      ...      ...                                 ...
995     ru    33747  br1-316  «Вот верный список впечатлений...»
996     ru    33747  br1-316  «Вот верный список впечатлений...»
997     ru    33747  br1-316  «Вот верный список впечатлений...»
998     ru    33747  br1-316  «Вот верный список впечатлений...»
999     ru    33747  br1-316  «Вот верный список впечатлений...»

     year_created_from  year_created_to  id_author       author_name  \
0               1821.0           1821.0        220  Baratynskij E.A.
1               1821.0           1821.0        220  Baratynskij E.A.
2               1821.0           1821.0        220  Baratynskij E.A.
3               1821.0           1821.0        220  Baratynskij E.A.
4               1821.0           1821.0        220  Baratynskij E.A.
..                 ...              ...        ...               ...
995             1834.0           1834.0        220  Baratynskij E.A.
996             1834.0           1834.0        220  Baratynskij E.A.
997             1834.0           1834.0        220  Baratynskij E.A.
998             1834.0           1834.0        220  Baratynskij E.A.
999             1834.0           1834.0        220  Baratynskij E.A.

         word     lemma                                           analysis
0    приятель  приятель  [{'analysis': [{'lex': 'приятель', 'gr': 'S,му...
1     строгий   строгий  [{'analysis': [{'lex': 'строгий', 'gr': 'A=(ви...
2          ты        ты  [{'analysis': [{'lex': 'ты', 'gr': 'SPRO,ед,2-...
3          не        не  [{'analysis': [{'lex': 'не', 'gr': 'PART='}], ...
4        прав    правый  [{'analysis': [{'lex': 'правый', 'gr': 'A=ед,к...
..        ...       ...                                                ...
995    утаить  утаивать  [{'analysis': [{'lex': 'утаивать', 'gr': 'V,пе...
996        их       они  [{'analysis': [{'lex': 'они', 'gr': 'SPRO,мн=(...
997       как       как  [{'analysis': [{'lex': 'как', 'gr': 'ADVPRO='}...
998    нибудь    нибудь  [{'analysis': [{'lex': 'нибудь', 'gr': 'ADVPRO...
999         и         и  [{'analysis': [{'lex': 'и', 'gr': 'CONJ='}], '...

[1000 rows x 11 columns]

In [17]:
df.to_csv('../data/poetree_ru_19c_lemma.csv')